// =============================================================================
// Mock FSS (금감원) Data — 개발용 목업 데이터
// API 키 없이 개발/테스트할 때 사용
// =============================================================================

import type { BankLoanProduct } from './fss';

export const MOCK_MORTGAGE_PRODUCTS: BankLoanProduct[] = [
  // KB국민은행
  {
    bankName: 'KB국민은행',
    productName: 'KB주택담보대출',
    rateType: 'fixed',
    rateTypeName: '고정금리',
    minRate: 3.72,
    maxRate: 4.85,
    avgRate: 4.28,
    repaymentType: '원리금균등상환',
    mortgageType: '아파트',
    loanLimit: '최대 5억원',
    earlyRepayFee: '1.2%',
  },
  {
    bankName: 'KB국민은행',
    productName: 'KB주택담보대출',
    rateType: 'variable',
    rateTypeName: '변동금리',
    minRate: 3.55,
    maxRate: 4.62,
    avgRate: 4.08,
    repaymentType: '원리금균등상환',
    mortgageType: '아파트',
    loanLimit: '최대 5억원',
    earlyRepayFee: '1.2%',
  },
  {
    bankName: 'KB국민은행',
    productName: 'KB스타주택담보대출',
    rateType: 'mixed',
    rateTypeName: '혼합금리',
    minRate: 3.65,
    maxRate: 4.72,
    avgRate: 4.18,
    repaymentType: '원리금균등상환',
    mortgageType: '아파트',
    loanLimit: '최대 5억원',
    earlyRepayFee: '1.0%',
  },

  // 신한은행
  {
    bankName: '신한은행',
    productName: '신한주택담보대출',
    rateType: 'fixed',
    rateTypeName: '고정금리',
    minRate: 3.78,
    maxRate: 4.92,
    avgRate: 4.35,
    repaymentType: '원리금균등상환',
    mortgageType: '아파트',
    loanLimit: '최대 5억원',
    earlyRepayFee: '1.4%',
  },
  {
    bankName: '신한은행',
    productName: '신한주택담보대출',
    rateType: 'variable',
    rateTypeName: '변동금리',
    minRate: 3.52,
    maxRate: 4.58,
    avgRate: 4.05,
    repaymentType: '원리금균등상환',
    mortgageType: '아파트',
    loanLimit: '최대 5억원',
    earlyRepayFee: '1.4%',
  },

  // 우리은행
  {
    bankName: '우리은행',
    productName: '우리주택담보대출',
    rateType: 'fixed',
    rateTypeName: '고정금리',
    minRate: 3.82,
    maxRate: 4.95,
    avgRate: 4.38,
    repaymentType: '원리금균등상환',
    mortgageType: '아파트',
    loanLimit: '최대 4억원',
    earlyRepayFee: '1.3%',
  },
  {
    bankName: '우리은행',
    productName: '우리주택담보대출',
    rateType: 'variable',
    rateTypeName: '변동금리',
    minRate: 3.58,
    maxRate: 4.65,
    avgRate: 4.11,
    repaymentType: '원리금균등상환',
    mortgageType: '아파트',
    loanLimit: '최대 4억원',
    earlyRepayFee: '1.3%',
  },

  // 하나은행
  {
    bankName: '하나은행',
    productName: '하나주택담보대출',
    rateType: 'fixed',
    rateTypeName: '고정금리',
    minRate: 3.75,
    maxRate: 4.88,
    avgRate: 4.31,
    repaymentType: '원리금균등상환',
    mortgageType: '아파트',
    loanLimit: '최대 5억원',
    earlyRepayFee: '1.2%',
  },
  {
    bankName: '하나은행',
    productName: '하나원큐주택담보대출',
    rateType: 'variable',
    rateTypeName: '변동금리',
    minRate: 3.50,
    maxRate: 4.55,
    avgRate: 4.02,
    repaymentType: '원리금균등상환',
    mortgageType: '아파트',
    loanLimit: '최대 5억원',
    earlyRepayFee: '1.1%',
  },

  // NH농협은행
  {
    bankName: 'NH농협은행',
    productName: 'NH주택담보대출',
    rateType: 'fixed',
    rateTypeName: '고정금리',
    minRate: 3.80,
    maxRate: 4.90,
    avgRate: 4.35,
    repaymentType: '원리금균등상환',
    mortgageType: '아파트',
    loanLimit: '최대 5억원',
    earlyRepayFee: '1.2%',
  },
  {
    bankName: 'NH농협은행',
    productName: 'NH주택담보대출',
    rateType: 'variable',
    rateTypeName: '변동금리',
    minRate: 3.56,
    maxRate: 4.60,
    avgRate: 4.08,
    repaymentType: '원리금균등상환',
    mortgageType: '아파트',
    loanLimit: '최대 5억원',
    earlyRepayFee: '1.2%',
  },

  // 카카오뱅크
  {
    bankName: '카카오뱅크',
    productName: '카카오뱅크 주택담보대출',
    rateType: 'fixed',
    rateTypeName: '고정금리',
    minRate: 3.68,
    maxRate: 4.78,
    avgRate: 4.23,
    repaymentType: '원리금균등상환',
    mortgageType: '아파트',
    loanLimit: '최대 5억원',
    earlyRepayFee: '1.0%',
  },
  {
    bankName: '카카오뱅크',
    productName: '카카오뱅크 주택담보대출',
    rateType: 'variable',
    rateTypeName: '변동금리',
    minRate: 3.48,
    maxRate: 4.52,
    avgRate: 4.00,
    repaymentType: '원리금균등상환',
    mortgageType: '아파트',
    loanLimit: '최대 5억원',
    earlyRepayFee: '1.0%',
  },
];

export const MOCK_RENT_PRODUCTS: BankLoanProduct[] = [
  // KB국민은행
  {
    bankName: 'KB국민은행',
    productName: 'KB전세자금대출',
    rateType: 'fixed',
    rateTypeName: '고정금리',
    minRate: 3.85,
    maxRate: 4.95,
    avgRate: 4.40,
    repaymentType: '만기일시상환',
    mortgageType: '전세보증금',
    loanLimit: '최대 3억원',
    earlyRepayFee: '0.8%',
  },
  {
    bankName: 'KB국민은행',
    productName: 'KB전세자금대출',
    rateType: 'variable',
    rateTypeName: '변동금리',
    minRate: 3.65,
    maxRate: 4.72,
    avgRate: 4.18,
    repaymentType: '만기일시상환',
    mortgageType: '전세보증금',
    loanLimit: '최대 3억원',
    earlyRepayFee: '0.8%',
  },

  // 신한은행
  {
    bankName: '신한은행',
    productName: '신한전세자금대출',
    rateType: 'fixed',
    rateTypeName: '고정금리',
    minRate: 3.90,
    maxRate: 5.02,
    avgRate: 4.46,
    repaymentType: '만기일시상환',
    mortgageType: '전세보증금',
    loanLimit: '최대 3억원',
    earlyRepayFee: '0.9%',
  },
  {
    bankName: '신한은행',
    productName: '신한전세자금대출',
    rateType: 'variable',
    rateTypeName: '변동금리',
    minRate: 3.68,
    maxRate: 4.78,
    avgRate: 4.23,
    repaymentType: '만기일시상환',
    mortgageType: '전세보증금',
    loanLimit: '최대 3억원',
    earlyRepayFee: '0.9%',
  },

  // 우리은행
  {
    bankName: '우리은행',
    productName: '우리전세자금대출',
    rateType: 'variable',
    rateTypeName: '변동금리',
    minRate: 3.70,
    maxRate: 4.80,
    avgRate: 4.25,
    repaymentType: '만기일시상환',
    mortgageType: '전세보증금',
    loanLimit: '최대 2억5천만원',
    earlyRepayFee: '0.7%',
  },

  // 하나은행
  {
    bankName: '하나은행',
    productName: '하나전세자금대출',
    rateType: 'fixed',
    rateTypeName: '고정금리',
    minRate: 3.88,
    maxRate: 4.98,
    avgRate: 4.43,
    repaymentType: '만기일시상환',
    mortgageType: '전세보증금',
    loanLimit: '최대 3억원',
    earlyRepayFee: '0.8%',
  },

  // NH농협은행
  {
    bankName: 'NH농협은행',
    productName: 'NH전세자금대출',
    rateType: 'variable',
    rateTypeName: '변동금리',
    minRate: 3.62,
    maxRate: 4.70,
    avgRate: 4.16,
    repaymentType: '만기일시상환',
    mortgageType: '전세보증금',
    loanLimit: '최대 3억원',
    earlyRepayFee: '0.8%',
  },

  // 카카오뱅크
  {
    bankName: '카카오뱅크',
    productName: '카카오뱅크 전세자금대출',
    rateType: 'variable',
    rateTypeName: '변동금리',
    minRate: 3.55,
    maxRate: 4.65,
    avgRate: 4.10,
    repaymentType: '만기일시상환',
    mortgageType: '전세보증금',
    loanLimit: '최대 3억원',
    earlyRepayFee: '0.5%',
  },
];
