// =============================================================================
// Mock MOLIT (국토부) Data -- 개발용 목업 데이터
// API 키 없이 개발/테스트할 때 사용
// =============================================================================

import type { RealEstateTransaction } from './molit';

/**
 * 강남구/서초구 기준 아파트 실거래 목업 데이터
 * 현실적인 단지명, 가격, 면적, 층수를 사용
 */
export const MOCK_APT_TRADE: RealEstateTransaction[] = [
  {
    dealAmount: 240000,
    buildYear: 2008,
    dealYear: 2026,
    dealMonth: 3,
    dealDay: 5,
    dong: '대치동',
    aptName: '래미안대치팰리스',
    area: 84.99,
    floor: 18,
    jibun: '316',
    regionCode: '11680',
    cancelDealType: '',
    dealType: '중개거래',
  },
  {
    dealAmount: 195000,
    buildYear: 2015,
    dealYear: 2026,
    dealMonth: 3,
    dealDay: 3,
    dong: '역삼동',
    aptName: '래미안역삼',
    area: 59.91,
    floor: 12,
    jibun: '677',
    regionCode: '11680',
    cancelDealType: '',
    dealType: '중개거래',
  },
  {
    dealAmount: 180000,
    buildYear: 2012,
    dealYear: 2026,
    dealMonth: 2,
    dealDay: 25,
    dong: '역삼동',
    aptName: '자이역삼',
    area: 84.92,
    floor: 22,
    jibun: '720',
    regionCode: '11680',
    cancelDealType: '',
    dealType: '중개거래',
  },
  {
    dealAmount: 155000,
    buildYear: 2019,
    dealYear: 2026,
    dealMonth: 2,
    dealDay: 18,
    dong: '대치동',
    aptName: '힐스테이트대치',
    area: 59.96,
    floor: 8,
    jibun: '501',
    regionCode: '11680',
    cancelDealType: '',
    dealType: '직거래',
  },
  {
    dealAmount: 250000,
    buildYear: 2004,
    dealYear: 2026,
    dealMonth: 2,
    dealDay: 10,
    dong: '도곡동',
    aptName: '도곡렉슬',
    area: 114.5,
    floor: 25,
    jibun: '188',
    regionCode: '11680',
    cancelDealType: '',
    dealType: '중개거래',
  },
  {
    dealAmount: 130000,
    buildYear: 2017,
    dealYear: 2026,
    dealMonth: 1,
    dealDay: 22,
    dong: '서초동',
    aptName: '래미안서초에스티지',
    area: 59.94,
    floor: 15,
    jibun: '1548',
    regionCode: '11650',
    cancelDealType: '',
    dealType: '중개거래',
  },
  {
    dealAmount: 210000,
    buildYear: 2009,
    dealYear: 2026,
    dealMonth: 1,
    dealDay: 15,
    dong: '반포동',
    aptName: '래미안퍼스티지',
    area: 84.97,
    floor: 20,
    jibun: '18-2',
    regionCode: '11650',
    cancelDealType: '',
    dealType: '중개거래',
  },
  {
    dealAmount: 168000,
    buildYear: 2020,
    dealYear: 2026,
    dealMonth: 1,
    dealDay: 10,
    dong: '서초동',
    aptName: '자이서초',
    area: 84.88,
    floor: 10,
    jibun: '1600',
    regionCode: '11650',
    cancelDealType: '',
    dealType: '중개거래',
  },
  {
    dealAmount: 80000,
    buildYear: 2005,
    dealYear: 2026,
    dealMonth: 3,
    dealDay: 8,
    dong: '역삼동',
    aptName: '역삼자이',
    area: 49.77,
    floor: 5,
    jibun: '725',
    regionCode: '11680',
    cancelDealType: '',
    dealType: '직거래',
  },
  {
    dealAmount: 115000,
    buildYear: 2011,
    dealYear: 2026,
    dealMonth: 2,
    dealDay: 7,
    dong: '잠원동',
    aptName: '신반포자이',
    area: 59.99,
    floor: 14,
    jibun: '10',
    regionCode: '11650',
    cancelDealType: '',
    dealType: '중개거래',
  },
  {
    dealAmount: 190000,
    buildYear: 2016,
    dealYear: 2026,
    dealMonth: 3,
    dealDay: 11,
    dong: '대치동',
    aptName: '힐스테이트대치아이파크',
    area: 114.48,
    floor: 30,
    jibun: '508',
    regionCode: '11680',
    cancelDealType: '',
    dealType: '중개거래',
  },
  {
    dealAmount: 145000,
    buildYear: 2013,
    dealYear: 2026,
    dealMonth: 1,
    dealDay: 28,
    dong: '방배동',
    aptName: '래미안방배아트힐',
    area: 84.95,
    floor: 7,
    jibun: '882',
    regionCode: '11650',
    cancelDealType: '',
    dealType: '중개거래',
  },
];

/**
 * 거래 취소 건 포함 목업 (필터링 테스트용)
 */
export const MOCK_APT_TRADE_WITH_CANCEL: RealEstateTransaction[] = [
  ...MOCK_APT_TRADE,
  {
    dealAmount: 200000,
    buildYear: 2010,
    dealYear: 2026,
    dealMonth: 2,
    dealDay: 1,
    dong: '역삼동',
    aptName: '취소된거래아파트',
    area: 84.99,
    floor: 16,
    jibun: '100',
    regionCode: '11680',
    cancelDealType: 'O',
    dealType: '중개거래',
  },
];
